### ISSUE TITLE
Public launch

### ISSUE THREAD

**Issue by Atinux** [nuxt-themes/docus#623]
- [x] Theme structure: #613 
- [x] Update documentation
- [x] Upgrade Nuxt Content docs and improve documentation
- [ ] Invite current Docus users to repo to help them upgrade and improve documentation

To consider if needed for initial launch dependending of the breaking changes caused:
- [ ] Remove TailwindCSS to use Design Tokens
- [ ] Use Elements
- [ ] Remove GitHub module
